"use client";

import { useLocale } from 'next-intl';
import { LegalPage } from "@/components/LegalPage";

const esSections = [
  {
    heading: "Política de Reembolsos, Cancelaciones y Devoluciones – ARNUG, S.A. DE C.V. (ROVIA)",
    content: "Última actualización: 23 de junio 2026.\n\nEsta política describe las condiciones bajo las cuales proceden cancelaciones, cambios, devoluciones y reembolsos respecto de los servicios que ofrecemos a través de nuestro sitio http://rovia.com.mx (en adelante el “Sitio”) y demás canales de venta. Al contratar nuestros servicios, aceptas esta Política de Reembolsos, así como los Términos y Condiciones y el Aviso de Privacidad aplicables."
  },
  {
    heading: "PRIMERA.- Tipos de servicios comprendidos",
    content: "A efectos de esta política, nuestros servicios se agrupan, de manera enunciativa, en las siguientes categorías:\n\nItinerarios digitales y guías descargables (por ejemplo, “Itinerario Económico Digital”, guías organizadas en PDF, mapas de lugares y recomendaciones de hospedaje).\n\nItinerarios personalizados y planes estratégicos (por ejemplo, “Itinerario Express”, “Itinerario de Pueblos Mágicos”, “Itinerario Gastronómico”, “Plan Travel Planner Profesional”, “Plan Concierge de Viaje”, “Paquete Explorador” y demás servicios donde diseñamos una propuesta a medida).\n\nExperiencias y actividades por persona (por ejemplo, sesiones de yoga, experiencias comunitarias, talleres, tours gastronómicos, experiencias de temazcal, circuitos de spa, tours de cenotes, experiencias culturales y de bienestar).\n\nPaquetes integrales o de viaje completo (por ejemplo, “Paquete Viaje Completo”, “Paquete Aventura Total”, “Retiro de Yoga”, “Retiros frente al mar” u otros que integren múltiples componentes).\n\nSalvo que se indique expresamente otra cosa en la descripción específica del servicio, esta política aplica a todas las categorías anteriores."
  },
  {
    heading: "2. Alcance general de los reembolsos",
    content: "En términos generales:\n\nPara itinerarios digitales y productos descargables, el reembolso es muy limitado, dado que se trata de contenido que puede ser utilizado de inmediato una vez entregado.\n\nPara itinerarios personalizados, planes estratégicos y servicios de concierge, el reembolso se vincula al grado de avance y al tiempo de trabajo ya invertido.\n\nPara experiencias y actividades por persona, aplican condiciones de cancelación y reembolso sujetas a plazos mínimos antes de la fecha programada y, en su caso, a las políticas de los prestadores locales.\n\nPara paquetes integrales, las condiciones pueden combinar elementos de las categorías anteriores y se indicarán en la propuesta o confirmación correspondiente.\n\nSiempre que la ley reconozca un derecho de cancelación o revocación a favor del consumidor para compras a distancia, lo respetaremos en los términos aplicables, especialmente cuando se trate de servicios no ejecutados al momento de la solicitud y dentro de los plazos legales."
  },
  {
    heading: "3. Itinerarios digitales y guías descargables",
    content: "Los itinerarios digitales, guías en PDF, mapas y demás productos descargables o consultables en línea son considerados servicios ya prestados desde el momento en que:\n\nSe te envía el archivo, enlace de descarga o acceso correspondiente, o\nSe habilita el acceso al contenido digital que has comprado.\n\nPor la naturaleza de estos productos, no se aceptan reembolsos una vez que el itinerario digital o la guía hayan sido entregados o puestos a tu disposición, salvo que:\n\nEl archivo o contenido entregado sea incorrecto (no corresponda al producto comprado), o\nExista un error imputable a nosotros que haga imposible el uso del material y no podamos corregirlo en un plazo razonable.\n\nEn esos casos, podremos optar entre reenviar el contenido correcto, corregir el material o, en última instancia, realizar un reembolso parcial o total, según corresponda."
  },
  {
    heading: "4. Itinerarios personalizados, planes estratégicos y concierge",
    content: "Para itinerarios personalizados, planes estratégicos, servicios de travel planner, concierge o cualquier servicio a medida, aplican los siguientes criterios generales:\n\nUna vez que hayas realizado el pago y hayamos iniciado el análisis, diseño del itinerario o preparación de la propuesta, existe un componente de trabajo intelectual y tiempo ya invertido.\n\nEn consecuencia, los reembolsos no serán automáticos y se valorará el nivel de avance del servicio al momento de tu solicitud de cancelación.\n\nComo regla general:\n\nSi solicitas la cancelación antes de que hayamos recibido la información necesaria para comenzar a trabajar y todavía no hayamos iniciado la elaboración, podremos evaluar un reembolso hasta por el 100% del monto pagado, menos comisiones bancarias o costos de procesamiento que no sean recuperables.\n\nSi ya hemos comenzado el diseño del itinerario o plan (por ejemplo, ya se te ha enviado un primer borrador, ruta base, lista de recomendaciones o esquema general), podremos ofrecer ajustes o modificaciones dentro del mismo servicio contratado, pero en principio no procederá un reembolso completo, pues el servicio ya se encuentra en ejecución.\n\nEn casos excepcionales y a nuestra discreción, podremos valorar reembolsos parciales cuando el avance sea mínimo y la cancelación responda a circunstancias de fuerza mayor debidamente acreditadas.\n\nEn todos los casos, buscaremos ofrecer opciones razonables, como reprogramar el servicio para nuevas fechas, ajustar el destino, reconvertir el plan a otro producto o dejar un saldo a favor dentro de un plazo determinado."
  },
  {
    heading: "5. Experiencias y actividades por persona",
    content: "Las experiencias, talleres, recorridos, tours y actividades con fecha y horario definidos (por ejemplo, sesiones de yoga, temazcales, tours gastronómicos, experiencias comunitarias, circuitos de spa, tours de cenotes, etc.) están sujetas a disponibilidad y requieren coordinación con uno o varios prestadores locales.\n\nSalvo que se indique otra cosa en la descripción de la experiencia o en la confirmación:\n\nSi deseas cancelar tu participación, deberás solicitarlo con al menos 72 horas de anticipación respecto a la hora de inicio prevista. Dentro de dicho plazo, podremos ofrecer reprogramación o, en su caso, un reembolso parcial o saldo a favor, considerando las políticas del proveedor local y los costos ya incurridos.\n\nLas cancelaciones realizadas fuera del plazo anterior, así como las incomparecencias (no-show) el día de la experiencia, normalmente no serán reembolsables, dado que se bloquean lugares y se generan costos para los prestadores.\n\nEn casos de condiciones climáticas extremas, cierres por parte de autoridades, causas de fuerza mayor o decisiones del proveedor que imposibiliten la realización de la experiencia, buscaremos alternativas como reprogramar, cambiar de actividad o, en su caso, gestionar reembolsos parciales o totales conforme lo permitan las políticas de los terceros involucrados.\n\nCuando la experiencia incluya componentes de terceros (por ejemplo, transporte local, entradas, guías comunitarios), las condiciones de reembolso también podrán estar sujetas a las políticas de dichos prestadores, lo cual se te informará en la medida de lo posible al momento de la contratación o confirmación."
  },
  {
    heading: "6. Paquetes y servicios integrales",
    content: "En el caso de paquetes integrales o de viaje completo, que combinan varios servicios (planeación, reservas, experiencias, acompañamiento, etc.), la política de reembolsos puede variar según:\n\nEl estado de avance de cada componente (algunos ya prestados, otros en curso y otros futuros).\nLas políticas de cancelación de los terceros que intervienen (hoteles, tours, transportes, centros de bienestar, etc.).\nLa fecha en que recibamos tu solicitud de cancelación en relación con las fechas de viaje y las condiciones de temporada.\n\nEn general, procuraremos desglosar en la propuesta o confirmación:\n\nQué parte del monto corresponde a nuestros servicios de planeación, coordinación o concierge, y\nQué parte corresponde a costos o reservas con terceros y bajo qué condiciones son reembolsables o no.\n\nCon base en lo anterior, podremos ofrecerte alternativas como: reprogramación, cambios de destino, cambios de fechas, sustitución de servicios, saldos a favor o, en su caso, reembolsos parciales respecto de aquellos componentes que aún sean recuperables."
  },
  {
    heading: "7. Derecho de cancelación o revocación en compras a distancia",
    content: "Cuando la legislación mexicana en materia de protección al consumidor reconozca un derecho de revocación o cancelación en ciertas compras realizadas por medios electrónicos o a distancia, lo respetaremos en los términos y plazos aplicables, particularmente cuando:\n\nSe trate de servicios no ejecutados al momento de la solicitud, y\nLa revocación se ejerza dentro del plazo legal (por ejemplo, dentro de 5 días hábiles en ciertos casos), salvo que por la naturaleza del servicio ya prestado o personalizado exista una excepción prevista en la propia ley.\n\nEn estos casos, evaluaremos caso por caso conforme al tipo de servicio, el grado de avance y las disposiciones aplicables, informándote claramente las opciones disponibles."
  },
  {
    heading: "8. Procedimiento para solicitar un reembolso o cancelación",
    content: "Para solicitar una cancelación, cambio o reembolso, deberás contactarnos a través del correo info@rovia.com.mx, o del medio de contacto indicado en tu confirmación, indicando al menos:\n\nTu nombre completo.\nEl correo con el que realizaste la compra.\nEl nombre del servicio o experiencia contratada.\nFecha prevista de la experiencia o periodo de viaje (si aplica).\nMotivo de la cancelación o solicitud de reembolso.\n\nEn algunos casos, podremos solicitar información adicional para evaluar la procedencia del reembolso, cambio o reprogramación (por ejemplo, evidencia de un evento de fuerza mayor o documentos que acrediten la imposibilidad de viajar).\n\nTe responderemos en un plazo razonable, informándote la opción que resulte aplicable conforme a esta política, las condiciones de los prestadores involucrados y, en su caso, la legislación vigente."
  },
  {
    heading: "9. Forma y plazo de los reembolsos",
    content: "Cuando proceda un reembolso:\n\nEn la medida de lo posible, se realizará a través del mismo método de pago utilizado en la compra original (por ejemplo, devolución a la tarjeta utilizada), salvo que técnicamente no sea viable y se acuerde otro método contigo.\n\nEl plazo para que el reembolso se vea reflejado puede variar según la institución financiera o plataforma de pago; te informaremos el plazo estimado de procesamiento y cualquier referencia disponible.\n\nEn algunos casos, podremos ofrecer saldos a favor para futuros servicios, cuando ello resulte más conveniente para ambas partes o sea la opción más viable dadas las políticas de terceros."
  },
  {
    heading: "10. Casos en los que no procede reembolso",
    content: "Sin perjuicio de otros supuestos señalados en esta política, en términos generales no procederá reembolso cuando:\n\nSe trate de productos digitales o itinerarios ya entregados y correctamente funcionales.\nLa cancelación se solicite fuera de los plazos mínimos establecidos para experiencias o actividades con fecha definida.\nSe trate de incomparecencias (no-show) o llegadas tardías que impidan la prestación del servicio.\nLa imposibilidad de recibir el servicio derive de información incorrecta proporcionada por la persona usuaria, incumplimiento de requisitos, negativa a seguir instrucciones de seguridad o conducta inadecuada.\nEl servicio ya haya sido prestado en su totalidad o en una proporción tal que la devolución del monto resulte incompatible con la naturaleza del trabajo realizado."
  },
  {
    heading: "11. Quejas y aclaraciones",
    content: "Si tienes alguna inconformidad, queja o aclaración relacionada con cancelaciones, reembolsos o cargos, podrás contactarnos en el correo info@rovia.com.mx o por los medios de contacto publicados en el Sitio.\n\nAtenderemos tu caso con la mayor diligencia posible, y, cuando corresponda, te informaremos sobre los mecanismos de conciliación disponibles ante las autoridades de protección al consumidor u otras instancias competentes."
  }
];

const enSections = [
  {
    heading: "Refund, Cancellation and Return Policy – ARNUG, S.A. DE C.V. (ROVIA)",
    content: "Last update: June 23, 2026.\n\nThis policy describes the conditions under which cancellations, changes, returns, and refunds apply regarding the services we offer through our website http://rovia.com.mx (hereinafter the “Site”) and other sales channels. By contracting our services, you accept this Refund Policy, as well as the applicable Terms and Conditions and Privacy Notice."
  },
  {
    heading: "FIRST.- Types of covered services",
    content: "For the purposes of this policy, our services are grouped, including but not limited to, the following categories:\n\nDigital itineraries and downloadable guides (for example, “Digital Budget Itinerary”, guides organized in PDF, location maps, and accommodation recommendations).\n\nPersonalized itineraries and strategic plans (for example, “Express Itinerary”, “Magical Towns Itinerary”, “Gastronomic Itinerary”, “Professional Travel Planner Plan”, “Travel Concierge Plan”, “Explorer Package” and other services where we design a tailor-made proposal).\n\nExperiences and activities per person (for example, yoga sessions, community experiences, workshops, gastronomic tours, temazcal experiences, spa circuits, cenote tours, cultural and wellness experiences).\n\nComprehensive or full travel packages (for example, “Complete Travel Package”, “Total Adventure Package”, “Yoga Retreat”, “Beachfront Retreats” or others that integrate multiple components).\n\nUnless expressly stated otherwise in the specific description of the service, this policy applies to all the above categories."
  },
  {
    heading: "2. General scope of refunds",
    content: "In general terms:\n\nFor digital itineraries and downloadable products, refunds are very limited, given that it is content that can be used immediately once delivered.\n\nFor personalized itineraries, strategic plans, and concierge services, the refund is linked to the degree of progress and the work time already invested.\n\nFor experiences and activities per person, cancellation and refund conditions apply subject to minimum notice periods prior to the scheduled date and, where appropriate, the policies of local providers.\n\nFor comprehensive packages, conditions may combine elements of the previous categories and will be indicated in the corresponding proposal or confirmation.\n\nWhenever the law recognizes a cancellation or revocation right in favor of the consumer for distance purchases, we will respect it under the applicable terms, especially when it concerns services not executed at the time of the request and within the legal deadlines."
  },
  {
    heading: "3. Digital itineraries and downloadable guides",
    content: "Digital itineraries, PDF guides, maps, and other downloadable or online consultative products are considered services already provided from the moment:\n\nThe file, download link, or corresponding access is sent to you, or\nAccess is enabled to the digital content you have purchased.\n\nDue to the nature of these products, refunds are not accepted once the digital itinerary or guide has been delivered or made available to you, unless:\n\nThe delivered file or content is incorrect (does not correspond to the purchased product), or\nThere is an error attributable to us that makes the use of the material impossible and we cannot correct it within a reasonable time.\n\nIn those cases, we may choose to resend the correct content, correct the material, or, ultimately, issue a partial or full refund, as appropriate."
  },
  {
    heading: "4. Personalized itineraries, strategic plans, and concierge",
    content: "For personalized itineraries, strategic plans, travel planner services, concierge, or any tailor-made service, the following general criteria apply:\n\nOnce you have made the payment and we have started the analysis, itinerary design, or proposal preparation, there is a component of intellectual work and time already invested.\n\nConsequently, refunds will not be automatic, and the level of progress of the service will be evaluated at the time of your cancellation request.\n\nAs a general rule:\n\nIf you request a cancellation before we have received the necessary information to start working and we have not yet started the preparation, we may evaluate a refund of up to 100% of the amount paid, minus bank commissions or processing costs that are not recoverable.\n\nIf we have already started the design of the itinerary or plan (for example, a first draft, base route, list of recommendations, or general scheme has already been sent to you), we may offer adjustments or modifications within the same contracted service, but in principle, a full refund will not apply, as the service is already in execution.\n\nIn exceptional cases and at our discretion, we may evaluate partial refunds when the progress is minimal and the cancellation responds to duly proven force majeure circumstances.\n\nIn all cases, we will seek to offer reasonable options, such as rescheduling the service for new dates, adjusting the destination, converting the plan to another product, or leaving a credit balance within a specified period."
  },
  {
    heading: "5. Experiences and activities per person",
    content: "Experiences, workshops, tours, and activities with defined dates and times (for example, yoga sessions, temazcales, gastronomic tours, community experiences, spa circuits, cenote tours, etc.) are subject to availability and require coordination with one or several local providers.\n\nUnless otherwise indicated in the experience description or confirmation:\n\nIf you wish to cancel your participation, you must request it at least 72 hours in advance of the scheduled start time. Within this period, we may offer rescheduling or, where appropriate, a partial refund or credit balance, considering the local provider's policies and the costs already incurred.\n\nCancellations made outside the aforementioned period, as well as no-shows on the day of the experience, will normally not be refundable, since spaces are blocked and costs are generated for the providers.\n\nIn cases of extreme weather conditions, closures by authorities, force majeure causes, or provider decisions that make it impossible to carry out the experience, we will seek alternatives such as rescheduling, changing the activity, or, where appropriate, managing partial or total refunds as permitted by the policies of the involved third parties.\n\nWhen the experience includes third-party components (e.g., local transport, tickets, community guides), refund conditions may also be subject to the policies of these providers, which will be informed to you as much as possible at the time of contracting or confirmation."
  },
  {
    heading: "6. Packages and comprehensive services",
    content: "In the case of comprehensive or full travel packages, which combine several services (planning, reservations, experiences, accompaniment, etc.), the refund policy may vary depending on:\n\nThe state of progress of each component (some already provided, others ongoing, and others future).\nThe cancellation policies of the intervening third parties (hotels, tours, transport, wellness centers, etc.).\nThe date we receive your cancellation request in relation to the travel dates and seasonal conditions.\n\nIn general, we will strive to break down in the proposal or confirmation:\n\nWhat part of the amount corresponds to our planning, coordination, or concierge services, and\nWhat part corresponds to costs or reservations with third parties and under what conditions they are refundable or not.\n\nBased on the above, we may offer you alternatives such as: rescheduling, destination changes, date changes, substitution of services, credit balances, or, where appropriate, partial refunds for those components that are still recoverable."
  },
  {
    heading: "7. Right of cancellation or revocation in distance purchases",
    content: "When Mexican consumer protection legislation recognizes a right of revocation or cancellation for certain purchases made through electronic or distance means, we will respect it under the applicable terms and deadlines, particularly when:\n\nIt concerns services not executed at the time of the request, and\nThe revocation is exercised within the legal period (for example, within 5 business days in certain cases), unless an exception provided by the law itself exists due to the nature of the already provided or personalized service.\n\nIn these cases, we will evaluate case by case according to the type of service, the degree of progress, and the applicable provisions, clearly informing you of the available options."
  },
  {
    heading: "8. Procedure to request a refund or cancellation",
    content: "To request a cancellation, change, or refund, you must contact us via email at info@rovia.com.mx, or through the contact method indicated in your confirmation, providing at least:\n\nYour full name.\nThe email used to make the purchase.\nThe name of the contracted service or experience.\nScheduled date of the experience or travel period (if applicable).\nReason for the cancellation or refund request.\n\nIn some cases, we may request additional information to evaluate the appropriateness of the refund, change, or rescheduling (for example, evidence of a force majeure event or documents proving the inability to travel).\n\nWe will respond within a reasonable time, informing you of the option that applies according to this policy, the conditions of the involved providers, and, where appropriate, current legislation."
  },
  {
    heading: "9. Form and timeframe of refunds",
    content: "When a refund applies:\n\nAs far as possible, it will be made through the same payment method used in the original purchase (for example, return to the card used), unless it is technically unfeasible and another method is agreed upon with you.\n\nThe timeframe for the refund to be reflected may vary depending on the financial institution or payment platform; we will inform you of the estimated processing time and any available reference.\n\nIn some cases, we may offer credit balances for future services, when this is more convenient for both parties or is the most viable option given third-party policies."
  },
  {
    heading: "10. Cases in which a refund does not apply",
    content: "Without prejudice to other scenarios indicated in this policy, in general terms, a refund will not apply when:\n\nIt concerns digital products or itineraries already delivered and properly functional.\nThe cancellation is requested outside the minimum deadlines established for experiences or activities with a defined date.\nIt involves no-shows or late arrivals that prevent the provision of the service.\nThe inability to receive the service derives from incorrect information provided by the user, failure to comply with requirements, refusal to follow safety instructions, or inappropriate conduct.\nThe service has already been provided in its entirety or in such a proportion that returning the amount is incompatible with the nature of the work performed."
  },
  {
    heading: "11. Complaints and clarifications",
    content: "If you have any disagreement, complaint, or clarification related to cancellations, refunds, or charges, you can contact us at info@rovia.com.mx or through the contact methods published on the Site.\n\nWe will address your case with the utmost diligence and, where appropriate, inform you about the conciliation mechanisms available before consumer protection authorities or other competent instances."
  }
];

export default function PoliticaDeReembolsos() {
  const locale = useLocale();
  const isEnglish = locale === 'en';
  
  const title = isEnglish ? "Refund, Cancellation and Return Policy" : "Política de Reembolsos y Cancelaciones";
  const sections = isEnglish ? enSections : esSections;

  return <LegalPage title={title} sections={sections} />;
}